overrides:
  "@react-native/assets-registry": "0.74.87"
  metro-cache-key: "0.80.12"
  metro-transform-plugins: "0.80.12"
  metro-transform-worker: "0.80.12"
  metro-source-map: "0.80.12"
  metro-runtime: "0.80.12"
  metro-resolver: "0.80.12"
  metro-file-map: "0.80.12"
  metro-babel-transformer: "0.80.12"
  metro-config: "0.80.12"
  metro-core: "0.80.12"
